AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DynamoDBTableNameSuffix:
    Type: String

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub User${DynamoDBTableNameSuffix}
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  SessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Session${DynamoDBTableNameSuffix}
      AttributeDefinitions:
        - AttributeName: SessionId
          AttributeType: S
      KeySchema:
        - AttributeName: SessionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    DependsOn:
      - UserTable

  ItemTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub Item${DynamoDBTableNameSuffix}
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: CreatedAt
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
        - AttributeName: CreatedAt
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
    DependsOn:
      - SessionTable
