version = 0.1

[default]
[default.local_start_api]
[default.local_start_api.parameters]
port = 8080
parameter_overrides = """
  DynamoDBTableNameSuffix=-local \
  DynamoDBEndpointUrl=http://dynamodb:8000 \
"""

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "learn-sam-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vy7zad7rv34o"
s3_prefix = "learn-sam-dev"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = """
  DynamoDBTableNameSuffix=-dev \
  DynamoDBEndpointUrl=https://dynamodb.ap-northeast-1.amazonaws.com \
"""
