AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  learn-sam

  Sample SAM Template for learn-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: python3.8
    Handler: app.lambda_handler

Resources:
  ListItemsFunction:
    # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/items/list_items
      Events:
        ApiGatewayIntegration:
          Type: Api
          Properties:
            Path: /items
            Method: get

  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/items/get_item
      Events:
        ApiGatewayIntegration:
          Type: Api
          Properties:
            Path: /items/{item_id}
            Method: get
