AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  learn-sam

  Sample SAM Template for learn-sam

Parameters:
  DynamoDBTableName:
    Type: String
  DynamoDBEndpointUrl:
    Type: String

Globals:
  Function:
    Timeout: 10
    Runtime: python3.8
    Handler: app.lambda_handler
    Environment:
      Variables:
        DynamoDBTableName: !Sub ${DynamoDBTableName}
        DynamoDBEndpointUrl: !Sub ${DynamoDBEndpointUrl}
    Layers:
      - !Ref BaseLayer

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${DynamoDBTableName}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10

  BaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/layers/base_layer
    Metadata:
      BuildMethod: python3.8

  ListItemsFunction:
    # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/apis/items/list_items
      Events:
        ApiGatewayIntegration:
          Type: Api
          Properties:
            Path: /items
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub ${DynamoDBTableName}

  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/apis/items/get_item
      Events:
        ApiGatewayIntegration:
          Type: Api
          Properties:
            Path: /items/{item_id}
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub ${DynamoDBTableName}

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/apis/auth/login
      Events:
        ApiGatewayIntegration:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub ${DynamoDBTableName}
