AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DynamoDBEndpointUrl:
    Type: String
  DynamoDBTableNameSuffix:
    Type: String

Globals:
  Function:
    Timeout: 10
    Runtime: python3.8
    Handler: app.lambda_handler.lambda_handler
    Environment:
      Variables:
        DynamoDBEndpointUrl: !Sub ${DynamoDBEndpointUrl}
        DynamoDBTableNameSuffix: !Sub ${DynamoDBTableNameSuffix}
    Layers:
      - !Ref BaseLayer

Resources:
  BaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/layers/base_layer
    Metadata:
      BuildMethod: python3.8

  ListItemsFunction:
    # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/apis/items/list_items
      Events:
        ApiGatewayIntegration:
          Type: Api
          Properties:
            Path: /items
            Method: get

  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/apis/items/get_item
      Events:
        ApiGatewayIntegration:
          Type: Api
          Properties:
            Path: /items/{item_id}
            Method: get

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/apis/auth/login
      Events:
        ApiGatewayIntegration:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub User${DynamoDBTableNameSuffix}
        - DynamoDBCrudPolicy:
            TableName: !Sub Session${DynamoDBTableNameSuffix}
